/**
 * Markup for the feature-oriented HTML report. Kept apart from the reporter so
 * the look of the report can be changed without touching result collection.
 */

export const BUCKETS = ['passed', 'failed', 'broken', 'skipped', 'other'] as const;

export type Bucket = (typeof BUCKETS)[number];

export type Totals = Record<Bucket, number>;

export type StepReport = {
  title: string;
  durationMs: number;
  failed: boolean;
};

export type AttachmentReport = {
  name: string;
  /** Report-relative link, absent for attachments held in memory. */
  href?: string;
  /** Original location on disk, carried through to the JSON summary. */
  path?: string;
  isImage: boolean;
};

export type ScenarioReport = {
  name: string;
  project: string;
  location: string;
  bucket: Bucket;
  flaky: boolean;
  durationMs: number;
  retries: number;
  tags: string[];
  steps: StepReport[];
  annotations: { type: string; description?: string }[];
  error?: string;
  attachments: AttachmentReport[];
  /** Web vitals lifted out of the attachment, when the scenario captured them. */
  performance?: Record<string, number>;
};

export type FeatureReport = {
  name: string;
  path: string;
  totals: Totals;
  durationMs: number;
  scenarios: ScenarioReport[];
};

export type RunReport = {
  status: string;
  startedAt: string;
  durationMs: number;
  totals: Totals;
  flaky: number;
  features: FeatureReport[];
};

const BUCKET_LABELS: Record<Bucket, string> = {
  passed: 'Passed',
  failed: 'Failed',
  broken: 'Broken',
  skipped: 'Skipped',
  other: 'Other',
};

export function renderFeatureReport(run: RunReport): string {
  const total = sum(run.totals);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Feature report — BrainPOP</title>
<style>${STYLES}</style>
</head>
<body>
<header>
  <div class="title">
    <h1>Feature report</h1>
    <span class="run-status ${run.status === 'passed' ? 'ok' : 'bad'}">${esc(run.status)}</span>
  </div>
  <p class="meta">${total} test${total === 1 ? '' : 's'} across ${run.features.length} feature file${
    run.features.length === 1 ? '' : 's'
  } · ${formatDuration(run.durationMs)} · ${esc(run.startedAt)}</p>
</header>

<section class="totals">
  ${BUCKETS.map((bucket) => card(bucket, run.totals[bucket], total)).join('')}
  ${run.flaky > 0 ? `<div class="card flaky"><span class="count">${run.flaky}</span><span class="label">Flaky</span></div>` : ''}
</section>

${bar(run.totals)}

<section class="controls">
  <span class="controls-label">Show</span>
  ${BUCKETS.map(
    (bucket) =>
      `<button class="chip ${bucket}" data-filter="${bucket}" aria-pressed="true">${BUCKET_LABELS[bucket]}</button>`,
  ).join('')}
  <button class="chip plain" id="expand-all">Expand all</button>
  <button class="chip plain" id="collapse-all">Collapse all</button>
</section>

<main>
${run.features.map(feature).join('\n')}
</main>

<footer>
  <p>Generated by <code>featureReporter</code>, which also writes <code>summary.json</code>.
  Traces, videos, and step timelines live in the
  Playwright HTML report (<code>npx playwright show-report</code>).</p>
</footer>

<script>${SCRIPT}</script>
</body>
</html>
`;
}

function card(bucket: Bucket, count: number, total: number): string {
  const pct = total === 0 ? 0 : Math.round((count / total) * 100);
  return `<div class="card ${bucket}">
    <span class="count">${count}</span>
    <span class="label">${BUCKET_LABELS[bucket]}</span>
    <span class="pct">${pct}%</span>
  </div>`;
}

function bar(totals: Totals): string {
  const total = sum(totals);
  if (total === 0) {
    return '';
  }
  const segments = BUCKETS.filter((bucket) => totals[bucket] > 0)
    .map(
      (bucket) =>
        `<span class="seg ${bucket}" style="width:${(totals[bucket] / total) * 100}%" title="${
          BUCKET_LABELS[bucket]
        }: ${totals[bucket]}"></span>`,
    )
    .join('');
  return `<div class="bar">${segments}</div>`;
}

function feature(item: FeatureReport): string {
  const total = sum(item.totals);
  const worst = worstBucket(item.totals);
  return `<details class="feature" data-buckets="${bucketsPresent(item.totals).join(' ')}">
  <summary>
    <span class="dot ${worst}"></span>
    <span class="feature-name">${esc(item.name)}</span>
    <span class="feature-path">${esc(item.path)}</span>
    <span class="counts">${BUCKETS.filter((bucket) => item.totals[bucket] > 0)
      .map((bucket) => `<span class="pill ${bucket}">${item.totals[bucket]} ${BUCKET_LABELS[bucket].toLowerCase()}</span>`)
      .join('')}</span>
    <span class="feature-duration">${formatDuration(item.durationMs)}</span>
  </summary>
  <div class="feature-body">
    ${bar(item.totals)}
    <p class="feature-meta">${total} scenario run${total === 1 ? '' : 's'} including every project</p>
    ${item.scenarios.map(scenario).join('\n')}
  </div>
</details>`;
}

function scenario(item: ScenarioReport): string {
  const hasDetail =
    item.error !== undefined ||
    item.steps.length > 0 ||
    item.attachments.length > 0 ||
    item.annotations.length > 0;

  const head = `<span class="dot ${item.bucket}"></span>
    <span class="scenario-name">${esc(item.name)}</span>
    ${item.flaky ? '<span class="pill flaky">flaky</span>' : ''}
    ${item.retries > 0 ? `<span class="pill retry">${item.retries} retr${item.retries === 1 ? 'y' : 'ies'}</span>` : ''}
    <span class="pill project">${esc(item.project)}</span>
    ${item.tags.map((tag) => `<span class="pill tag">${esc(tag)}</span>`).join('')}
    <span class="scenario-duration">${formatDuration(item.durationMs)}</span>`;

  if (!hasDetail) {
    return `<div class="scenario static" data-bucket="${item.bucket}">${head}</div>`;
  }

  return `<details class="scenario" data-bucket="${item.bucket}">
  <summary>${head}</summary>
  <div class="scenario-body">
    ${item.steps.length > 0 ? steps(item.steps) : ''}
    ${item.error ? `<pre class="error">${esc(item.error)}</pre>` : ''}
    ${item.annotations.length > 0 ? annotations(item.annotations) : ''}
    ${item.attachments.length > 0 ? attachments(item.attachments) : ''}
  </div>
</details>`;
}

function steps(list: StepReport[]): string {
  return `<ol class="steps">${list
    .map(
      (step) =>
        `<li class="${step.failed ? 'failed' : ''}"><span>${esc(step.title)}</span><span class="step-duration">${formatDuration(
          step.durationMs,
        )}</span></li>`,
    )
    .join('')}</ol>`;
}

function annotations(list: { type: string; description?: string }[]): string {
  return `<div class="annotations">${list
    .map(
      (item) =>
        `<span class="annotation"><b>${esc(item.type)}</b>${
          item.description ? ` ${esc(item.description)}` : ''
        }</span>`,
    )
    .join('')}</div>`;
}

function attachments(list: AttachmentReport[]): string {
  const images = list.filter((item) => item.isImage && item.href);
  const files = list.filter((item) => !images.includes(item));

  const gallery =
    images.length > 0
      ? `<div class="attachments">${images
          .map(
            (item) =>
              `<figure><img loading="lazy" src="${esc(item.href ?? '')}" alt="${esc(
                item.name,
              )}"><figcaption>${esc(item.name)}</figcaption></figure>`,
          )
          .join('')}</div>`
      : '';

  const links =
    files.length > 0
      ? `<div class="attachment-links">${files
          .map((item) =>
            item.href
              ? `<a class="attachment" href="${esc(item.href)}">${esc(item.name)}</a>`
              : `<span class="attachment">${esc(item.name)}</span>`,
          )
          .join('')}</div>`
      : '';

  return gallery + links;
}

function bucketsPresent(totals: Totals): Bucket[] {
  return BUCKETS.filter((bucket) => totals[bucket] > 0);
}

function worstBucket(totals: Totals): Bucket {
  const severity: Bucket[] = ['failed', 'broken', 'other', 'skipped', 'passed'];
  return severity.find((bucket) => totals[bucket] > 0) ?? 'passed';
}

function sum(totals: Totals): number {
  return BUCKETS.reduce((acc, bucket) => acc + totals[bucket], 0);
}

export function formatDuration(ms: number): string {
  if (ms < 1000) {
    return `${Math.round(ms)}ms`;
  }
  const seconds = ms / 1000;
  if (seconds < 60) {
    return `${seconds.toFixed(1)}s`;
  }
  const minutes = Math.floor(seconds / 60);
  return `${minutes}m ${Math.round(seconds % 60)}s`;
}

function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const STYLES = `
:root {
  --passed: #22a06b; --failed: #d64545; --broken: #d98324;
  --skipped: #8a94a6; --other: #7a5af5; --flaky: #c99a06;
  --bg: #f5f6f8; --panel: #ffffff; --ink: #1c2333; --muted: #6b7280; --line: #e3e6ec;
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 24px; background: var(--bg); color: var(--ink);
  font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}
header { margin-bottom: 20px; }
.title { display: flex; align-items: center; gap: 12px; }
h1 { font-size: 22px; margin: 0; }
.run-status {
  text-transform: uppercase; font-size: 11px; font-weight: 700; letter-spacing: .06em;
  padding: 3px 9px; border-radius: 999px; color: #fff;
}
.run-status.ok { background: var(--passed); }
.run-status.bad { background: var(--failed); }
.meta { color: var(--muted); margin: 6px 0 0; }

.totals { display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 14px; }
.card {
  background: var(--panel); border: 1px solid var(--line); border-top: 3px solid var(--line);
  border-radius: 8px; padding: 12px 18px; min-width: 116px;
}
.card .count { display: block; font-size: 26px; font-weight: 700; line-height: 1.1; }
.card .label { display: block; color: var(--muted); font-size: 12px; }
.card .pct { color: var(--muted); font-size: 11px; }
.card.passed { border-top-color: var(--passed); }
.card.failed { border-top-color: var(--failed); }
.card.broken { border-top-color: var(--broken); }
.card.skipped { border-top-color: var(--skipped); }
.card.other { border-top-color: var(--other); }
.card.flaky { border-top-color: var(--flaky); }

.bar { display: flex; height: 8px; border-radius: 999px; overflow: hidden; background: var(--line); margin-bottom: 18px; }
.seg.passed { background: var(--passed); } .seg.failed { background: var(--failed); }
.seg.broken { background: var(--broken); } .seg.skipped { background: var(--skipped); }
.seg.other { background: var(--other); }

.controls { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; margin-bottom: 16px; }
.controls-label { color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: .05em; }
.chip {
  border: 1px solid var(--line); background: var(--panel); color: var(--ink);
  border-radius: 999px; padding: 4px 12px; font-size: 12px; cursor: pointer;
}
.chip[aria-pressed="false"] { opacity: .4; text-decoration: line-through; }
.chip.passed { border-color: var(--passed); } .chip.failed { border-color: var(--failed); }
.chip.broken { border-color: var(--broken); } .chip.skipped { border-color: var(--skipped); }
.chip.other { border-color: var(--other); }

.feature { background: var(--panel); border: 1px solid var(--line); border-radius: 8px; margin-bottom: 10px; }
.feature > summary, .scenario > summary, .scenario.static {
  display: flex; align-items: center; gap: 10px; flex-wrap: wrap;
  padding: 12px 14px; cursor: pointer; list-style: none;
}
.scenario.static { cursor: default; }
summary::-webkit-details-marker { display: none; }
.feature > summary:hover, .scenario > summary:hover { background: #fafbfc; }
.feature-name { font-weight: 600; }
.feature-path, .feature-meta { color: var(--muted); font-size: 12px; }
.feature-duration, .scenario-duration { margin-left: auto; color: var(--muted); font-size: 12px; }
.feature-body { padding: 0 14px 12px; border-top: 1px solid var(--line); }
.feature-body .bar { margin: 12px 0 6px; }

.dot { width: 9px; height: 9px; border-radius: 50%; flex: none; }
.dot.passed { background: var(--passed); } .dot.failed { background: var(--failed); }
.dot.broken { background: var(--broken); } .dot.skipped { background: var(--skipped); }
.dot.other { background: var(--other); }

.pill {
  font-size: 11px; padding: 2px 8px; border-radius: 999px;
  background: #eef0f4; color: var(--muted); white-space: nowrap;
}
.pill.passed { background: #e4f4ed; color: #16714a; }
.pill.failed { background: #fbe6e6; color: #a12b2b; }
.pill.broken { background: #fdf0e0; color: #96591a; }
.pill.skipped { background: #eef0f4; color: #5a6473; }
.pill.other { background: #eeeafe; color: #4c34b8; }
.pill.flaky { background: #fdf4d6; color: #8a6a04; }
.pill.retry { background: #fdf4d6; color: #8a6a04; }
.pill.tag { background: #e8eefc; color: #2d4c9b; }

.scenario { border-top: 1px solid var(--line); }
.scenario:first-of-type { border-top: none; }
.scenario-name { font-weight: 500; }
.scenario-body { padding: 4px 14px 16px 33px; }

.steps { margin: 0 0 12px; padding-left: 18px; color: #384153; }
.steps li { display: flex; gap: 12px; padding: 2px 0; }
.steps li span:first-child { flex: 1; }
.steps li.failed { color: var(--failed); font-weight: 600; }
.step-duration { color: var(--muted); font-size: 12px; }

.error {
  background: #fff5f5; border: 1px solid #f3c9c9; border-radius: 6px; color: #7f1d1d;
  padding: 10px 12px; overflow-x: auto; white-space: pre-wrap; font-size: 12px; margin: 0 0 12px;
}
.annotations { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 12px; }
.annotation { font-size: 11px; background: #eef0f4; border-radius: 4px; padding: 2px 8px; color: #384153; }
.attachments { display: flex; flex-wrap: wrap; gap: 12px; align-items: flex-start; }
.attachments img { max-width: 320px; border: 1px solid var(--line); border-radius: 6px; display: block; }
.attachments figure { margin: 0; }
.attachments figcaption { color: var(--muted); font-size: 11px; margin-top: 4px; }
.attachment-links { display: flex; flex-wrap: wrap; gap: 14px; margin-top: 10px; }
.attachment { font-size: 12px; color: #2d4c9b; }
footer { margin-top: 24px; color: var(--muted); font-size: 12px; }
code { background: #eef0f4; padding: 1px 5px; border-radius: 4px; }
`;

const SCRIPT = `
(() => {
  const hidden = new Set();

  const apply = () => {
    document.querySelectorAll('.scenario').forEach((row) => {
      row.style.display = hidden.has(row.dataset.bucket) ? 'none' : '';
    });
    document.querySelectorAll('.feature').forEach((feature) => {
      const buckets = (feature.dataset.buckets || '').split(' ').filter(Boolean);
      const visible = buckets.some((bucket) => !hidden.has(bucket));
      feature.style.display = visible ? '' : 'none';
    });
  };

  document.querySelectorAll('.chip[data-filter]').forEach((chip) => {
    chip.addEventListener('click', () => {
      const bucket = chip.dataset.filter;
      const on = chip.getAttribute('aria-pressed') === 'true';
      chip.setAttribute('aria-pressed', String(!on));
      if (on) hidden.add(bucket); else hidden.delete(bucket);
      apply();
    });
  });

  const setAll = (open) => document.querySelectorAll('details').forEach((d) => { d.open = open; });
  document.getElementById('expand-all').addEventListener('click', () => setAll(true));
  document.getElementById('collapse-all').addEventListener('click', () => setAll(false));

  // Failures are the reason anyone opens this, so surface them without a click.
  document.querySelectorAll('.feature').forEach((feature) => {
    const buckets = (feature.dataset.buckets || '').split(' ');
    if (buckets.includes('failed') || buckets.includes('broken')) {
      feature.open = true;
      feature.querySelectorAll('.scenario[data-bucket="failed"], .scenario[data-bucket="broken"]')
        .forEach((row) => { row.open = true; });
    }
  });
})();
`;
